const window_products = {
  "cadeiras-1": {
    "id": "cadeiras-1",
    "name": "Cama Paris Cama Viena",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-2": {
    "id": "cadeiras-2",
    "name": "Quartos de Casal a por no site O QUE SE VENDE MAIS - LINHA PARIS",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-3": {
    "id": "cadeiras-3",
    "name": "Ibiza BASE TV PARIS",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-4": {
    "id": "cadeiras-4",
    "name": "MESA CENTRO PARIS Dark Grey - Carvalho (Dark Grey - Oak)",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-5": {
    "id": "cadeiras-5",
    "name": "City - mesa COMPLEMENTO PARIS",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-6": {
    "id": "cadeiras-6",
    "name": "Faro APARADOR PARIS",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-7": {
    "id": "cadeiras-7",
    "name": "Toronto MESA PARIS",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quartos-8": {
    "id": "quartos-8",
    "name": "Málaga - tudo e por tbm elemento 4 prateleiras! CADEIRAS LOURO?",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-9": {
    "id": "cadeiras-9",
    "name": "Madrid CAMA CASAL PARIS",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-10": {
    "id": "cadeiras-10",
    "name": "Florença MESAS DE CABECEIRA PARIS",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-11": {
    "id": "cadeiras-11",
    "name": "Paris - principal COMODA PARIS CINZA",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-12": {
    "id": "cadeiras-12",
    "name": "Estoril CAMISEIRO PARIS",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-13": {
    "id": "cadeiras-13",
    "name": "Chiado Dark Grey - Carvalho (Dark Grey - Oak)",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-14": {
    "id": "cadeiras-14",
    "name": "Viena e salas",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-15": {
    "id": "cadeiras-15",
    "name": "madrid",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-16": {
    "id": "cadeiras-16",
    "name": "paris",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-17": {
    "id": "cadeiras-17",
    "name": "chiado",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-18": {
    "id": "cadeiras-18",
    "name": "viena",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-19": {
    "id": "cadeiras-19",
    "name": "cadeiras moon",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-20": {
    "id": "cadeiras-20",
    "name": "sagres",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-21": {
    "id": "cadeiras-21",
    "name": "charly",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-22": {
    "id": "cadeiras-22",
    "name": "paris",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-23": {
    "id": "cadeiras-23",
    "name": "milão",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-24": {
    "id": "cadeiras-24",
    "name": "viena",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cadeiras-25": {
    "id": "cadeiras-25",
    "name": "prateleira com costa madrid",
    "price": 0.0,
    "url": "cadeiras.html",
    "description": "Cores e medidas personalizáveis. Preço sob consulta.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo na Loja[+0.00]",
    "image": "images/sem-imagem.svg"
  }
};
