const window_products = {
  "quarto-1": {
    "id": "quarto-1",
    "name": "Cama de Casal Lourini Faro",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-2": {
    "id": "quarto-2",
    "name": "Cama de Casal Lourini Viena",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-3": {
    "id": "quarto-3",
    "name": "Cama Estofada Lourini Sophie",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-4": {
    "id": "quarto-4",
    "name": "Cabeceira Lourini Elegance",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-5": {
    "id": "quarto-5",
    "name": "Cabeceira Lourini Gomo",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-6": {
    "id": "quarto-6",
    "name": "Cabeceira Lourini Krystal",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-7": {
    "id": "quarto-7",
    "name": "Mesa de Cabeceira Lourini Ibiza",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-8": {
    "id": "quarto-8",
    "name": "Mesa de Cabeceira Lourini Toronto",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-9": {
    "id": "quarto-9",
    "name": "Mesa de Cabeceira Lourini Sevilha",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-10": {
    "id": "quarto-10",
    "name": "Cómoda Lourini Málaga",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-11": {
    "id": "quarto-11",
    "name": "Cómoda Lourini City",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-12": {
    "id": "quarto-12",
    "name": "Cómoda Lourini Paris",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-13": {
    "id": "quarto-13",
    "name": "Roupeiro Lourini Sevilha",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-14": {
    "id": "quarto-14",
    "name": "Roupeiro Lourini Toledo",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-15": {
    "id": "quarto-15",
    "name": "Roupeiro Lourini Viena",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-16": {
    "id": "quarto-16",
    "name": "Camiseiro Lourini Sevilha",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-17": {
    "id": "quarto-17",
    "name": "Camiseiro Lourini Toledo",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-18": {
    "id": "quarto-18",
    "name": "Sommier Estofado Lourini Letto",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-19": {
    "id": "quarto-19",
    "name": "Sommier Rebatível Lourini Sintra",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "quarto-20": {
    "id": "quarto-20",
    "name": "Estrado Metálico Lourini",
    "price": 0.0,
    "url": "quartos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-1": {
    "id": "sala-1",
    "name": "Sofá Chaise Longue Lourini Robson",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-2": {
    "id": "sala-2",
    "name": "Sofá Chaise Longue Lourini Deryl",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-3": {
    "id": "sala-3",
    "name": "Sofá de Canto Lourini Amazónia",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-4": {
    "id": "sala-4",
    "name": "Sofá de Canto Lourini Deryl Relax",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-5": {
    "id": "sala-5",
    "name": "Sofá de Canto Lourini Megan",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-6": {
    "id": "sala-6",
    "name": "Sofá Chaise Longue Lourini Sabrina",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-7": {
    "id": "sala-7",
    "name": "Sofá Fixo 3 Lugares Lourini Viena",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-8": {
    "id": "sala-8",
    "name": "Móvel de TV Lourini Málaga",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-9": {
    "id": "sala-9",
    "name": "Móvel de TV Lourini Toronto",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-10": {
    "id": "sala-10",
    "name": "Móvel de TV Lourini City",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-11": {
    "id": "sala-11",
    "name": "Móvel de TV Lourini Ibiza",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-12": {
    "id": "sala-12",
    "name": "Aparador de Sala Lourini Málaga",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-13": {
    "id": "sala-13",
    "name": "Aparador de Sala Lourini Toronto",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-14": {
    "id": "sala-14",
    "name": "Estante de Livros Lourini Málaga",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-15": {
    "id": "sala-15",
    "name": "Mesa de Jantar Lourini Jasmin",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-16": {
    "id": "sala-16",
    "name": "Mesa de Jantar Lourini Tulipa",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-17": {
    "id": "sala-17",
    "name": "Mesa de Jantar Lourini Sevilha",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-18": {
    "id": "sala-18",
    "name": "Cadeira de Jantar Lourini Sintra",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-19": {
    "id": "sala-19",
    "name": "Cadeira de Jantar Lourini Letto",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "sala-20": {
    "id": "sala-20",
    "name": "Cadeira de Jantar Lourini Denver",
    "price": 0.0,
    "url": "salas.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-1": {
    "id": "colchao-1",
    "name": "Colchão Molas Ensacadas Lourini Gold",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-2": {
    "id": "colchao-2",
    "name": "Colchão Viscoelástico Lourini Sense",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-3": {
    "id": "colchao-3",
    "name": "Colchão Espuma Alta Densidade Lourini",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-4": {
    "id": "colchao-4",
    "name": "Colchão Ortopédico Lourini Medical",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-5": {
    "id": "colchao-5",
    "name": "Colchão Molas Bonel Lourini Classic",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-6": {
    "id": "colchao-6",
    "name": "Colchão Híbrido Lourini Titanium",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-7": {
    "id": "colchao-7",
    "name": "Colchão de Berço Lourini Baby",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-8": {
    "id": "colchao-8",
    "name": "Colchão Anti-alérgico Lourini Protect",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-9": {
    "id": "colchao-9",
    "name": "Colchão Ergonómico Lourini Active",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-10": {
    "id": "colchao-10",
    "name": "Colchão Termorregulador Lourini Climate",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-11": {
    "id": "colchao-11",
    "name": "Almofada Viscoelástica Lourini Ergo",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-12": {
    "id": "colchao-12",
    "name": "Almofada de Látex Lourini Soft",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-13": {
    "id": "colchao-13",
    "name": "Protetor de Colchão Impermeável",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-14": {
    "id": "colchao-14",
    "name": "Capa de Colchão Anti-Ácaros Lourini",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-15": {
    "id": "colchao-15",
    "name": "Sobrecolchão Viscoelástico Topper",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-16": {
    "id": "colchao-16",
    "name": "Almofada Cervical Lourini Comfort",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-17": {
    "id": "colchao-17",
    "name": "Pés para Sommier Lourini Metal",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-18": {
    "id": "colchao-18",
    "name": "Pés para Sommier Lourini Madeira",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-19": {
    "id": "colchao-19",
    "name": "Estrado de Ripas Fixo Lourini",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "colchao-20": {
    "id": "colchao-20",
    "name": "Kit de União para Camas Lourini",
    "price": 0.0,
    "url": "colchoes.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-1": {
    "id": "kids-1",
    "name": "Cama Infantil Lourini Dream Azul",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-2": {
    "id": "kids-2",
    "name": "Cama Infantil Lourini Dream Rosa",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-3": {
    "id": "kids-3",
    "name": "Cama Infantil Lourini Dream Verde",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-4": {
    "id": "kids-4",
    "name": "Cama Ninho Infantil Lourini Star",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-5": {
    "id": "kids-5",
    "name": "Beliche Infantil Lourini Compact",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-6": {
    "id": "kids-6",
    "name": "Secretária Juvenil Lourini Play",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-7": {
    "id": "kids-7",
    "name": "Roupeiro Infantil Lourini Joy",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-8": {
    "id": "kids-8",
    "name": "Colchão Juvenil Lourini Junior Molas",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-9": {
    "id": "kids-9",
    "name": "Colchão Juvenil Lourini Junior Espuma",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-10": {
    "id": "kids-10",
    "name": "Colchão Juvenil Lourini Junior Visco",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-11": {
    "id": "kids-11",
    "name": "Colchão Juvenil Anti-Ácaros Lourini",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-12": {
    "id": "kids-12",
    "name": "Colchão Juvenil Ortopédico Lourini",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-13": {
    "id": "kids-13",
    "name": "Colchão Juvenil Respirável Lourini",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-14": {
    "id": "kids-14",
    "name": "Colchão Juvenil Compacto Lourini",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-15": {
    "id": "kids-15",
    "name": "Almofada Juvenil Lourini Soft",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-16": {
    "id": "kids-16",
    "name": "Protetor de Colchão Infantil Impermeável",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-17": {
    "id": "kids-17",
    "name": "Mesa de Cabeceira Juvenil Lourini Play",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-18": {
    "id": "kids-18",
    "name": "Estante de Brinquedos Infantil",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-19": {
    "id": "kids-19",
    "name": "Módulo de Gavetas Juvenil Lourini",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "kids-20": {
    "id": "kids-20",
    "name": "Prateleira Juvenil Lourini Joy",
    "price": 0.0,
    "url": "kids.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-1": {
    "id": "escritorio-1",
    "name": "Secretária de Escritório Lourini City",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-2": {
    "id": "escritorio-2",
    "name": "Secretária de Escritório Lourini Faro",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-3": {
    "id": "escritorio-3",
    "name": "Secretária de Escritório Lourini Dream",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-4": {
    "id": "escritorio-4",
    "name": "Secretária de Escritório Lourini Málaga",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-5": {
    "id": "escritorio-5",
    "name": "Secretária de Escritório Lourini Toronto",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-6": {
    "id": "escritorio-6",
    "name": "Secretária de Escritório Lourini Sevilha",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-7": {
    "id": "escritorio-7",
    "name": "Secretária com Alçado Lourini Office",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-8": {
    "id": "escritorio-8",
    "name": "Secretária Escandinava Lourini Nord",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-9": {
    "id": "escritorio-9",
    "name": "Secretária Suspensa Lourini Space",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-10": {
    "id": "escritorio-10",
    "name": "Estante de Escritório Lourini Málaga",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-11": {
    "id": "escritorio-11",
    "name": "Estante de Escritório Lourini Toronto",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-12": {
    "id": "escritorio-12",
    "name": "Estante de Escritório Lourini Sevilha",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-13": {
    "id": "escritorio-13",
    "name": "Armário de Escritório Lourini Málaga",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-14": {
    "id": "escritorio-14",
    "name": "Armário de Escritório Lourini Toronto",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-15": {
    "id": "escritorio-15",
    "name": "Cadeira de Escritório Ergonómica",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-16": {
    "id": "escritorio-16",
    "name": "Cadeira de Escritório Direção Comfort",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-17": {
    "id": "escritorio-17",
    "name": "Mesa de Reunião Lourini City",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-18": {
    "id": "escritorio-18",
    "name": "Mesa de Reunião Lourini Faro",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-19": {
    "id": "escritorio-19",
    "name": "Módulo de Arquivo de Escritório",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "escritorio-20": {
    "id": "escritorio-20",
    "name": "Prateleira de Escritório Lourini",
    "price": 0.0,
    "url": "escritorio.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-1": {
    "id": "cozinha-1",
    "name": "Mesa de Cozinha Extensível Jasmin",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-2": {
    "id": "cozinha-2",
    "name": "Mesa de Cozinha Extensível Tulipa",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-3": {
    "id": "cozinha-3",
    "name": "Mesa de Cozinha Extensível Huelva",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-4": {
    "id": "cozinha-4",
    "name": "Mesa de Cozinha Extensível Madrid",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-5": {
    "id": "cozinha-5",
    "name": "Mesa de Cozinha Extensível Badajoz",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-6": {
    "id": "cozinha-6",
    "name": "Mesa de Cozinha Extensível Zeus",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-7": {
    "id": "cozinha-7",
    "name": "Mesa de Cozinha Extensível Sevilha",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-8": {
    "id": "cozinha-8",
    "name": "Mesa de Cozinha Extensível Toledo",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-9": {
    "id": "cozinha-9",
    "name": "Mesa de Cozinha Livro Málaga",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-10": {
    "id": "cozinha-10",
    "name": "Mesa de Cozinha Fixa Eiffel",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-11": {
    "id": "cozinha-11",
    "name": "Cadeira de Cozinha Lourini Sintra",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-12": {
    "id": "cozinha-12",
    "name": "Cadeira de Cozinha Lourini Letto",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-13": {
    "id": "cozinha-13",
    "name": "Cadeira de Cozinha Lourini Denver",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-14": {
    "id": "cozinha-14",
    "name": "Cadeira de Cozinha Lourini Logan",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-15": {
    "id": "cozinha-15",
    "name": "Cadeira de Cozinha Lourini Diosa",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-16": {
    "id": "cozinha-16",
    "name": "Banco Alto de Cozinha Lourini Sintra",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-17": {
    "id": "cozinha-17",
    "name": "Banco Alto de Cozinha Lourini Letto",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-18": {
    "id": "cozinha-18",
    "name": "Banco Alto de Cozinha Lourini Denver",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-19": {
    "id": "cozinha-19",
    "name": "Aparador de Cozinha Lourini Málaga",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "cozinha-20": {
    "id": "cozinha-20",
    "name": "Armário de Parede Cozinha Lourini",
    "price": 0.0,
    "url": "cozinha.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-1": {
    "id": "complemento-1",
    "name": "Aparador Complemento Lourini Málaga",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-2": {
    "id": "complemento-2",
    "name": "Aparador Complemento Lourini Malmo",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-3": {
    "id": "complemento-3",
    "name": "Aparador Complemento Lourini Toronto",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-4": {
    "id": "complemento-4",
    "name": "Aparador Complemento Lourini Faro",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-5": {
    "id": "complemento-5",
    "name": "Aparador Complemento Lourini City",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-6": {
    "id": "complemento-6",
    "name": "Aparador Complemento Lourini Ibiza",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-7": {
    "id": "complemento-7",
    "name": "Consola de Entrada Lourini Málaga",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-8": {
    "id": "complemento-8",
    "name": "Consola de Entrada Lourini Toronto",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-9": {
    "id": "complemento-9",
    "name": "Consola de Entrada Lourini Ibiza",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-10": {
    "id": "complemento-10",
    "name": "Sapateira Lourini Málaga",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-11": {
    "id": "complemento-11",
    "name": "Sapateira Lourini Toronto",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-12": {
    "id": "complemento-12",
    "name": "Sapateira Lourini Sevilha",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-13": {
    "id": "complemento-13",
    "name": "Sapateira Lourini City",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-14": {
    "id": "complemento-14",
    "name": "Sapateira Lourini Ibiza",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-15": {
    "id": "complemento-15",
    "name": "Sapateira de Design Lourini Málaga",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-16": {
    "id": "complemento-16",
    "name": "Bengaleiro Lourini Málaga",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-17": {
    "id": "complemento-17",
    "name": "Bengaleiro Lourini Toronto",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-18": {
    "id": "complemento-18",
    "name": "Bengaleiro Lourini Ibiza",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-19": {
    "id": "complemento-19",
    "name": "Bengaleiro Lourini City",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  },
  "complemento-20": {
    "id": "complemento-20",
    "name": "Bengaleiro Lourini Sevilha",
    "price": 0.0,
    "url": "complementos.html",
    "description": "Mobiliário Lourini de alta qualidade. Cores, acabamentos e medidas personalizáveis após a encomenda na nossa loja física.",
    "custom1_name": "Dimensões",
    "custom1_options": "Standard[+0.00]|Personalizado (sob consulta)[+0.00]",
    "custom2_name": "Tecido / Cor",
    "custom2_options": "Ver Catálogo de Tecidos[+0.00]",
    "image": "images/sem-imagem.svg"
  }
};

if (typeof window !== 'undefined') {
  window.produtos = window_products;
}
